# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GerarHash.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from hashlib import sha256,sha1,sha512,md5

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 366)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txbMd5 = QtWidgets.QLineEdit(self.centralwidget)
        self.txbMd5.setGeometry(QtCore.QRect(120, 70, 350, 20))
        self.txbMd5.setObjectName("txbMd5")
        self.txbTexto_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txbTexto_2.setGeometry(QtCore.QRect(120, 100, 350, 20))
        self.txbTexto_2.setObjectName("txbTexto_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 130, 51, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 160, 41, 16))
        self.label_5.setObjectName("label_5")
        self.txbTexto = QtWidgets.QLineEdit(self.centralwidget)
        self.txbTexto.setGeometry(QtCore.QRect(120, 40, 350, 20))
        self.txbTexto.setObjectName("txbTexto")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 51, 16))
        self.label_3.setObjectName("label_3")
        self.txbTexto_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.txbTexto_3.setGeometry(QtCore.QRect(120, 130, 350, 20))
        self.txbTexto_3.setObjectName("txbTexto_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 81, 16))
        self.label.setObjectName("label")
        self.btnGerar = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.gerar_hash())
        self.btnGerar.setGeometry(QtCore.QRect(390, 230, 75, 71))
        self.btnGerar.setObjectName("btnGerar")
        self.txbTexto_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.txbTexto_4.setGeometry(QtCore.QRect(120, 160, 350, 20))
        self.txbTexto_4.setObjectName("txbTexto_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def gerar_hash(self):
        texto = str(self.txbTexto.text())
        
        obj_md5 = md5(texto.encode('utf-8')).hexdigest()
        obj_sha1 = sha1(texto.encode('utf-8')).hexdigest()
        obj_sha256 = sha256(texto.encode('utf-8')).hexdigest()
        obj_sha512 = sha512(texto.encode('utf-8')).hexdigest()
        
        self.txbMd5.setText(obj_md5)
        self.txbTexto_2.setText(obj_sha1)
        self.txbTexto_3.setText(obj_sha256)
        self.txbTexto_4.setText(obj_sha512)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "SHA 512 : "))
        self.label_2.setText(_translate("MainWindow", "MD5 : "))
        self.label_5.setText(_translate("MainWindow", "SHA 1 : "))
        self.label_3.setText(_translate("MainWindow", "SHA 256 : "))
        self.label.setText(_translate("MainWindow", "Insira o texto :"))
        self.btnGerar.setText(_translate("MainWindow", "Gerar hash"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
